version: '3.8'

services:
  flask_api:
    build: .
    container_name: flask_api
    depends_on:
      - mongo_db
      - chroma_db
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/product_db
      - CHROMA_PATH=/database/chroma

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  chroma_db:
    image: chromadb/chroma
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/database/chroma

volumes:
  mongo_data:
  chroma_data:
